name: Deploy-Page

on:
  push:
    release:
      types: 
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GitHub_Token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: /